USE [master]
GO

/****** Object:  Database [BD_SISTEMA_DE_PARKING]    Script Date: 2/11/2023 10:21:30 ******/
CREATE DATABASE [BD_SISTEMA_DE_PARKING]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BD_COCHERA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLSERVER2016\MSSQL\DATA\BD_SISTEMA_DE_PARKING.mdf' , SIZE = 382976KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BD_COCHERA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLSERVER2016\MSSQL\DATA\BD_SISTEMA_DE_PARKING_0.ldf' , SIZE = 1008000KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BD_SISTEMA_DE_PARKING].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BD_SISTEMA_DE_PARKING] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BD_SISTEMA_DE_PARKING] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BD_SISTEMA_DE_PARKING] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BD_SISTEMA_DE_PARKING] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BD_SISTEMA_DE_PARKING] SET ARITHABORT OFF 
GO

ALTER DATABASE [BD_SISTEMA_DE_PARKING] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BD_SISTEMA_DE_PARKING] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BD_SISTEMA_DE_PARKING] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BD_SISTEMA_DE_PARKING] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BD_SISTEMA_DE_PARKING] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BD_SISTEMA_DE_PARKING] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BD_SISTEMA_DE_PARKING] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BD_SISTEMA_DE_PARKING] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BD_SISTEMA_DE_PARKING] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BD_SISTEMA_DE_PARKING] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BD_SISTEMA_DE_PARKING] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BD_SISTEMA_DE_PARKING] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BD_SISTEMA_DE_PARKING] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BD_SISTEMA_DE_PARKING] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BD_SISTEMA_DE_PARKING] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BD_SISTEMA_DE_PARKING] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BD_SISTEMA_DE_PARKING] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BD_SISTEMA_DE_PARKING] SET RECOVERY FULL 
GO

ALTER DATABASE [BD_SISTEMA_DE_PARKING] SET  MULTI_USER 
GO

ALTER DATABASE [BD_SISTEMA_DE_PARKING] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BD_SISTEMA_DE_PARKING] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BD_SISTEMA_DE_PARKING] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BD_SISTEMA_DE_PARKING] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BD_SISTEMA_DE_PARKING] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BD_SISTEMA_DE_PARKING] SET QUERY_STORE = OFF
GO

USE [BD_SISTEMA_DE_PARKING]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [BD_SISTEMA_DE_PARKING] SET  READ_WRITE 
GO

